"""empty message

Revision ID: 5b163c086853
Revises: ef23e211a975
Create Date: 2025-05-24 16:47:49.686750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b163c086853'
down_revision = 'ef23e211a975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('category', 'description',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'category', ['name'])
    op.alter_column('product', 'name',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('product', 'description',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('product', 'image',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('product', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'product', ['name'])
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.create_unique_constraint(None, 'role', ['name'])
    op.add_column('user', sa.Column('last_update', sa.DateTime(timezone=6), nullable=True))
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('user', 'recovery_code',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_column('user', 'date_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_updated', mysql.DATETIME(), nullable=True))
    op.alter_column('user', 'recovery_code',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    op.drop_column('user', 'last_update')
    op.drop_constraint(None, 'role', type_='unique')
    op.alter_column('role', 'name',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    op.drop_constraint(None, 'product', type_='unique')
    op.alter_column('product', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('product', 'image',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('product', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    op.drop_constraint(None, 'category', type_='unique')
    op.alter_column('category', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('category', 'name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
